// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: sentryclient.proto

package sentryclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEventReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg        string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XRequestId string `protobuf:"bytes,3,opt,name=x_request_id,json=xRequestId,proto3" json:"x_request_id,omitempty"`
	Detail     string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Collection string `protobuf:"bytes,5,opt,name=collection,proto3" json:"collection,omitempty"`
}

func (x *SendEventReq) Reset() {
	*x = SendEventReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sentryclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventReq) ProtoMessage() {}

func (x *SendEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_sentryclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventReq.ProtoReflect.Descriptor instead.
func (*SendEventReq) Descriptor() ([]byte, []int) {
	return file_sentryclient_proto_rawDescGZIP(), []int{0}
}

func (x *SendEventReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendEventReq) GetXRequestId() string {
	if x != nil {
		return x.XRequestId
	}
	return ""
}

func (x *SendEventReq) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *SendEventReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type EmptyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sentryclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_sentryclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_sentryclient_proto_rawDescGZIP(), []int{1}
}

var File_sentryclient_proto protoreflect.FileDescriptor

var file_sentryclient_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x22, 0x7a, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x0c, 0x78, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0b,
	0x0a, 0x09, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x32, 0x4c, 0x0a, 0x06, 0x53,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x42, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x73, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x73,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sentryclient_proto_rawDescOnce sync.Once
	file_sentryclient_proto_rawDescData = file_sentryclient_proto_rawDesc
)

func file_sentryclient_proto_rawDescGZIP() []byte {
	file_sentryclient_proto_rawDescOnce.Do(func() {
		file_sentryclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_sentryclient_proto_rawDescData)
	})
	return file_sentryclient_proto_rawDescData
}

var file_sentryclient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sentryclient_proto_goTypes = []interface{}{
	(*SendEventReq)(nil), // 0: sentryclient.SendEventReq
	(*EmptyResp)(nil),    // 1: sentryclient.EmptyResp
}
var file_sentryclient_proto_depIdxs = []int32{
	0, // 0: sentryclient.Sentry.SendEvent:input_type -> sentryclient.SendEventReq
	1, // 1: sentryclient.Sentry.SendEvent:output_type -> sentryclient.EmptyResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sentryclient_proto_init() }
func file_sentryclient_proto_init() {
	if File_sentryclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sentryclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendEventReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sentryclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sentryclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentryclient_proto_goTypes,
		DependencyIndexes: file_sentryclient_proto_depIdxs,
		MessageInfos:      file_sentryclient_proto_msgTypes,
	}.Build()
	File_sentryclient_proto = out.File
	file_sentryclient_proto_rawDesc = nil
	file_sentryclient_proto_goTypes = nil
	file_sentryclient_proto_depIdxs = nil
}
